Fixed "read locked" register issue.
boundarydevices/linux-imx6 pull request #66
Opened 2021-01-25 18:52 UTC by shitalkumar-gandhi

If user tries to access all the fuses in one go like "cat /sys/fsl_otp/HW_OCOTP*", then it will read all the registers including the read lock register.

For "read locked" registers 0xBADABADA will be returned and HW_OCOTP_CTRL[ERROR] will be set.

After this user will not be able to read/write any fuse value, in order to access any fuse value user has to reboot the device.

Hence this patch has been added to fix the same, so that user can read and write the fuse value after accessing all the values in one go i.e. cat /sys/fsl_otp/HW_OCOTP*.

2021-01-28 12:44 UTC, gibsson requested changes
Hi,
Please update your commit to include:
- proper title with mention of the driver being modified, like "char: fsl_otp: blah"
- proper commit log, your lines are too long, please use checkpatch.pl to ensure your patch respects Linux standard
- add you Signed-off-by signature
Overall, I'm not against that change, although I would recommend using the nvmem imx-ocotp driver instead of this one (which disappeared after 4.19). Here is the same thing as what you do for nvmem:
https://github.com/boundarydevices/linux-imx6/commit/9b66587ee
Regards,
Gary

2021-01-28 19:48 UTC, gibsson commented
I don't see any update of your patch, you only changed the PR title. You need to change the patch itself.

2021-01-29 06:53 UTC, shitalkumar-gandhi commented
@gibsson Done, Please re-review.

2021-01-29 08:04 UTC, gibsson commented
Almost good, why did you add "Update " in the title? Please remove.

2021-01-29 09:33 UTC, shitalkumar-gandhi commented
> Almost good, why did you add "Update " in the title? Please remove.

Ah..ok, removed

2021-01-29 09:40 UTC, merged

2021-01-29 09:40 UTC, gibsson commented
Thanks!